"""
Django settings for payment_service project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@n@*z8rtk7kj$d^#z^j3tfxnzzrz+_@4^1v%9&dk)-!$$hgbu-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
CORS_ALLOW_ALL_ORIGINS = True


CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-kopokopo-signature",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",   
# ]




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'payments',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'payment_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'payment_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


import dj_database_url
import os

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://payment_service_db_user:rIGsJR72WCAqboxmmor4TgK5PtrT7Ux5@dpg-d3f27g95pdvs73cdb86g-a.oregon-postgres.render.com/payment_service_db',
        conn_max_age=600,
        ssl_require=True
    )
}







# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# KopoKopo Config
# KOPOKOPO_CLIENT_ID = "Js5ut_8IIk902OutlIh4fmD-udEIU3TKjewvO8DM-f8"
# KOPOKOPO_CLIENT_SECRET = "1T9jQh3eymeaS0vjCNdsABqZPN85cVW6hTuQLceGv-Q"
# KOPOKOPO_TILL_NUMBER = "K317087"
# KOPOKOPO_BASE_URL = "https://api.kopokopo.com" 
# KOPOKOPO_CALLBACK_URL = "http://127.0.0.1:8000/api/payments/callback/"
# KOPOKOPO_API_KEY = "485b588c7d1a6e64cb0839282f7f543cbd1b5047"

# Laravel endpoint to update payment status
LARAVEL_UPDATE_URL = "https://testing.exotic-ads.com/api/payment/update"



# CyberSource Config
CYBERSOURCE_ACCESS_KEY = "be24a2df76553506bdb6328ee3fab082" 
CYBERSOURCE_PROFILE_ID = "6AF44E7A-8A82-4C4E-82FF-C9ABC436498D"
CYBERSOURCE_SECRET_KEY = "0ccbb472ebec4c7d98f3df6576e910d9b5b891ed55f54b6d9aa4b4fa122abde7ba5e1153d75b49618dc92f06576a400bd497049a1e6a4d2bb4f6ae5894eb258c8713467aea6b41e4acedb442f14d0bdf048abfb770f34e4bacd2ec56b632540ad41ffe560f954b74bf0c932a6552661b823a2a2483344e358d997fa7cb54d341"
CYBERSOURCE_API_URL = "https://secureacceptance.cybersource.com/pay"
CYBERSOURCE_RECEIPT_URL = "https://secureacceptance.cybersource.com/pay/api/cybersource/response/"
CYBERSOURCE_CANCEL_URL = "https://paymentservice-nwg5.onrender.com/api/cybersource/cancel/"

# settings.py

KOPOKOPO_CONFIGS = {
    "76": {  # Organization A
        "CLIENT_ID": "Js5ut_8IIk902OutlIh4fmD-udEIU3TKjewvO8DM-f8",
        "CLIENT_SECRET": "1T9jQh3eymeaS0vjCNdsABqZPN85cVW6hTuQLceGv-Q",
        "TILL_NUMBER": "K317087",
        "API_KEY": "485b588c7d1a6e64cb0839282f7f543cbd1b5047",
        "CALLBACK_URL": "https://090652d2b14b.ngrok-free.app/api/payments/callback/",
        "BASE_URL": "https://api.kopokopo.com",
    },
    "5": {  # Organization B
        "CLIENT_ID": "nKt8zIP6hTh1cEc-m75QhPbO72fvzyac9Vq-B9WwvHs",
        "CLIENT_SECRET": "HobdkVxyqlulmS5O3H8E8nsuRr6zJmOkKQ3h7sj13VQ",
        "TILL_NUMBER": "K987654",
        "API_KEY": "5ZovctTs7SxVzrwbZUtqswsi-GmP2m4i5gjsGtzj1d4",
        "CALLBACK_URL": "http://127.0.0.1:8000/api/payments/callback/",
        "BASE_URL": "https://sandbox.kopokopo.com",
    },
    "6": {  # Organization C
        "CLIENT_ID": "client_id_C",
        "CLIENT_SECRET": "client_secret_C",
        "TILL_NUMBER": "K111111",
        "API_KEY": "api_key_C",
        "CALLBACK_URL": "https://yourdomain.com/api/payments/callback/",
        "BASE_URL": "https://api.kopokopo.com",
    },
}

PARTNER_UPDATE_URL = "https://partnerdomain.com/api/payments/update"


