"""
Django settings for payment_service project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@n@*z8rtk7kj$d^#z^j3tfxnzzrz+_@4^1v%9&dk)-!$$hgbu-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'payment_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'payment_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# KopoKopo Config
KOPOKOPO_CLIENT_ID = "Js5ut_8IIk902OutlIh4fmD-udEIU3TKjewvO8DM-f8"
KOPOKOPO_CLIENT_SECRET = "1T9jQh3eymeaS0vjCNdsABqZPN85cVW6hTuQLceGv-Q"
KOPOKOPO_TILL_NUMBER = "K317087"
KOPOKOPO_BASE_URL = "https://api.kopokopo.com" 
KOPOKOPO_CALLBACK_URL = "https://30708230fdf8.ngrok-free.app/api/payments/callback/"
KOPOKOPO_API_KEY = "485b588c7d1a6e64cb0839282f7f543cbd1b5047"

# Laravel endpoint to update payment status
LARAVEL_UPDATE_URL = "https://api.exoticnairobi.com/api/payment/update"



# CyberSource Config
CYBERSOURCE_ACCESS_KEY = "02032c0e24703008b2b6b9674f94ce22"
CYBERSOURCE_PROFILE_ID = "3C05DAD8-9CA4-4350-A6D9-B0F606EB22D3"
CYBERSOURCE_SECRET_KEY = "14e2d79a83f84ddead2809585585126f63cdf5c1322d423eb9c56652a312d7c0fe9bf36cc44e4e9bafa8fd2f8a69c2c3abb7973afabb4766bd43b2b1e4e34f2e789952722615444dbc1914b06bbc9e0a830bf8fe83bd407fab3636a3ff3b8a7f9d304adc5f894d1bb856344da8152d8baf6ee6d784c54b279dd727f616e65ed6"
CYBERSOURCE_API_URL = "https://testsecureacceptance.cybersource.com/pay"
CYBERSOURCE_RECEIPT_URL = "https://ff33908d2eb8.ngrok-free.app/api/cybersource/response/"
CYBERSOURCE_CANCEL_URL = "https://ff33908d2eb8.ngrok-free.app/api/cybersource/cancel/"



