# Generated by Django 5.2.3 on 2025-08-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
