# Generated by Django 5.2.3 on 2025-08-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_currency_payment_payment_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='laravel_payment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
