# Generated by Django 5.2.3 on 2025-09-05 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_organization_paymentgatewayconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.organization'),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='base_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='callback_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='client_id',
            field=models.CharField(default='default_client_id_here', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='client_secret',
            field=models.CharField(default='default_client_secret_here', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='gateway',
            field=models.CharField(choices=[('KOPOKOPO', 'KopoKopo'), ('CYBERSOURCE', 'CyberSource')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_configs', to='payments.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentgatewayconfig',
            unique_together={('organization', 'gateway')},
        ),
    ]
