# Generated by Django 5.2.3 on 2025-11-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_organization_active_payment_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='mpesa_environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='mpesa_initiator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='mpesa_initiator_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='mpesa_passkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='gateway',
            field=models.CharField(choices=[('KOPOKOPO', 'KopoKopo'), ('CYBERSOURCE', 'CyberSource'), ('MPESA', 'M-PESA')], max_length=50),
        ),
    ]
